name: CMake

on:
  push:
    paths:
    - ".github/workflows/cmake.yml"
    - "**/CMakeLists.txt"
    - "Sources/SDLSwift/**"
    - "Sources/Examples/**/*.swift"
    - "Frameworks/**"
  pull_request:
    branches: [ "main" ]
    paths:
    - ".github/workflows/cmake.yml"
    - "**/CMakeLists.txt"
    - "Sources/SDLSwift/**"
    - "Sources/Examples/**/*.swift"
    - "Frameworks/**"

env:
  BUILD_TYPE: "RelWithDebInfo"

jobs:
  build:
    strategy:
      # Ensure that feedback is delivered for all matrix combinations
      fail-fast: false

      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build & install SDL3 (Ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      uses: libsdl-org/setup-sdl@4ebea449684c989388fe6bcea0460e300d13a5ae
      with:
        install-linux-dependencies: true
        version: sdl3-latest
        cmake-generator: Ninja

    - name: Configure CMake
      run: >
        cmake -GNinja -B ${{ github.workspace }}/build
        -DBUILD_TYPE:STRING=${{ env.BUILD_TYPE }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
