name: Swift Package

on:
  push:
    paths:
    - ".github/workflows/spm.yml"
    - "Package.swift"
    - "**.swift"
    - "Sources/CSDL3/**"
    - "Frameworks/**"
  pull_request:
    branches: [ "main" ]
    paths:
    - ".github/workflows/spm.yml"
    - "Package.swift"
    - "**.swift"
    - "Sources/CSDL3/**"
    - "Frameworks/**"

jobs:
  build:
    name: Swift Package - ${{ matrix.os }}
    strategy:
      # Ensure that feedback is delivered for all matrix combinations
      fail-fast: false

      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Swift
      uses: swift-actions/setup-swift@v2

    - name: Build & install SDL3 (Ubuntu)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      uses: libsdl-org/setup-sdl@4ebea449684c989388fe6bcea0460e300d13a5ae
      with:
        install-linux-dependencies: true
        version: sdl3-latest
        cmake-generator: Ninja

    - name: Build
      run: swift build

    - name: Run tests
      # Tests are broken with setup-sdl because of course they are
      if: ${{ ! startsWith(matrix.os, 'ubuntu') }}
      run: swift test
